### ISSUE TITLE
Unable to set NodeSelector, Tolerations and/or Affinity

### ISSUE THREAD

**Issue by kxcasa** [pact-foundation/pact-broker-chart#1]
The deployment template does not have placeholders for setting NodeSelector, Tolerations and/or Affinity. For my setup they would be particularly important.

**Comment by ChrisJBurns** [comment]
@kbcasagrande  Thanks for this. I'll give it a test and if all is good, we can merge this in.

**Comment by ChrisJBurns** [comment]
Added in: https://github.com/ChrisJBurns/pact-broker-chart/pull/3
