### ISSUE TITLE
Switching off basicAuth does not work

### ISSUE THREAD

**Issue by TomasMocek** [pact-foundation/pact-broker-chart#11]
Hello, this issue is closely related to the #9 .

Simply setting
```
basicAuth:
  enabled: false
```
  
Does not work, because the value is [automatically set to true if any credentials are provided](https://docs.pact.io/pact_broker/configuration/settings#basic_auth_enabled), and pact-broker-chart provides default values admin/admin.

Also, overriding default values with empty strings/nulls is not working, because in that case it [fails on reading it as an environment variables](https://github.com/ChrisJBurns/pact-broker-chart/blob/master/charts/pact-broker/templates/deployment.yaml#L127).

Thank you

**Comment by ChrisJBurns** [comment]
Hi @TomasMocek  good spot on the first point, I'll raise a PR to change this so there are no default values for `username` and `password`.

For your second point, on the `username` and `password` fields, I'll also add a `.Values.broker.config.basicAuth.enabled` check in there so the empty values in the first fix work :+1:

I'll try and get this in a PR by the end of the week - unless you beat me to it :)

**Comment by ChrisJBurns** [comment]
@TomasMocek Just merged the above, when the release has been made and you can pull it, let me know if it works the way you want it to :+1:

**Comment by TomasMocek** [comment]
Hello @ChrisJBurns , tested and works, thanks a lot!
