### ISSUE TITLE
Chart errors on unset `config.broker.basicAuth.readUser.{username,password}`

### ISSUE THREAD

**Issue by rmartine-ias** [pact-foundation/pact-broker-chart#13]
Currently, if basic auth is enabled, and `allowPublicRead` is true, a username and password for the read user are required. If unset, the chart constructs a `secretKeyRef` with an empty key and name, that then errors out in a somewhat confusing manner on the non-existent `key`.

Steps to reproduce:
`values.yaml`:
```yaml
broker:
  config:
    basicAuth:
      enabled: true
      allowPublicRead: true
      writeUser:
        username: admin
        password: hunter2
```
`helm install --dry-run --debug pact-broker pact-broker/pact-broker --values values.yml --version 0.2.1`

Result:
```
Error: INSTALLATION FAILED: unable to build kubernetes objects from release manifest: error validating "": error validating data: [ValidationError(Deployment.spec.template.spec.containers[0].env[26].valueFrom.secretKeyRef): missing required field "key" in io.k8s.api.core.v1.SecretKeySelector, ValidationError(Deployment.spec.template.spec.containers[0].env[27].valueFrom.secretKeyRef): missing required field "key" in io.k8s.api.core.v1.SecretKeySelector]
helm.go:84: [debug] error validating "": error validating data: [ValidationError(Deployment.spec.template.spec.containers[0].env[26].valueFrom.secretKeyRef): missing required field "key" in io.k8s.api.core.v1.SecretKeySelector, ValidationError(Deployment.spec.template.spec.containers[0].env[27].valueFrom.secretKeyRef): missing required field "key" in io.k8s.api.core.v1.SecretKeySelector]
```

I am not very proficient in helm, or the internal workings of the broker, but I think this could be resolved by changing the `else`s [here](https://github.com/ChrisJBurns/pact-broker-chart/blob/master/charts/pact-broker/templates/deployment.yaml#L149) and [here](https://github.com/ChrisJBurns/pact-broker-chart/blob/master/charts/pact-broker/templates/deployment.yaml#L160) to some kind of `else if .Values.broker.config.basicAuth.readUser.existingSecret`. Or maybe disabling the `readUser` if `publicRead` is true? But that might break things.

Thank you for making and maintaining this chart!

**Comment by ChrisJBurns** [comment]
@rmartine-ias  Thanks for raising this, I shall have a look in a bit more detail and try and get a fix up ASAP :+1:

For context, the default values were taken out in this [PR](https://github.com/ChrisJBurns/pact-broker-chart/pull/12) to address the issue raised in https://github.com/ChrisJBurns/pact-broker-chart/issues/11.

One last thing, this repo will be transferred over to the `pact-foundation` soon just so things are under the same Github Org - however I will still be the main maintainer :) So if you try to come back to this repository, it may not be in the same place the last time you looked. If I don't get the fix in before then, I will make sure to tag you in the new repo :+1:

**Comment by rmartine-ias** [comment]
Thank you for the reply, context, and heads up!

**Comment by ChrisJBurns** [comment]
@rmartine-ias Apologies for the late fix - has been a busy end of year :) Give it a try now with version `0.2.3` when it has been built and made available.
