### ISSUE TITLE
Corrects Release URL's to New Location

### ISSUE THREAD

**Issue by ChrisJBurns** [pact-foundation/pact-broker-chart#14]
As the `pact-broker-chart` has been transferred from my personal Github and into the Pact Foundation, we need to ensure that all URL's work and users can pull in the new Helm Charts from their own locations.

This includes changes to:
- The Github Page releases
- ArtifactHub

**Comment by Zhann** [comment]
Hi ChrisJBurns,

First off, thank you for your work on this.

Is there any way around it now?

Currently:

```
helm repo add pact-broker https://chrisjburns.github.io/pact-broker-chart 
Error: looks like "https://chrisjburns.github.io/pact-broker-chart" is not a valid chart repository or cannot be reached: failed to fetch https://chrisjburns.github.io/pact-broker-chart/index.yaml : 404 Not Found
```

I'm not that familiar with GitHub pages, but currently the deployment link on https://github.com/pact-foundation/pact-broker-chart/deployments/activity_log?environment=github-pages shows the same 404.

**Comment by ChrisJBurns** [comment]
@Zhann  Have got a [PR](https://github.com/pact-foundation/pact-broker-chart/pull/16) up to change the URL's to the new pact-foundation ones. Give them a try and let me know :+1:

**Comment by dabde** [comment]
@ChrisJBurns Currently it's not yet working, related the github-pages environment is showing to the wrong location. For this, I think you need to re-trigger the last master build. 

But then, the `index.yaml` from the gh-pages repo, is still pointing for old artefacts to the wrong location. Maybe this need a manual fix.

**Comment by ChrisJBurns** [comment]
@dabde 

If you run the folllowing:
```bash
helm repo add pact-broker https://pact-foundation.github.io/pact-broker-chart/
helm install pact-broker pact-broker/pact-broker
```

You should be able to pull the Charts? I can pull the latest chart as well as pull older versions.
`helm pull pact-broker/pact-broker --version 0.2.0`

I can update the `index.yaml` also just for brevity, but you should be able to pull any Chart version using the commands above

**Comment by Zhann** [comment]
> @Zhann Have got a [PR](https://github.com/pact-foundation/pact-broker-chart/pull/16) up to change the URL's to the new pact-foundation ones. Give them a try and let me know 👍

This worked for me. Thank you for the resolution! :-)
