### ISSUE TITLE
Defaults have to be capital

### ISSUE THREAD

**Issue by ChrisJBurns** [pact-foundation/pact-broker-chart#17]
https://github.com/pact-foundation/pact-broker-chart/blob/b2e7a5de5c8323f4822190200af4f52510cc4fa9/charts/pact-broker/values.yaml#L75

**Comment by knechtionscoding** [comment]
@ChrisJBurns Does this mean that the defaults should all be uppercased? when they are passed in? Based on the pactbroker docs I read it seemed they should be lowercased

**Comment by ChrisJBurns** [comment]
Ah, not sure why I felt they had to be uppercased. Closing
