### ISSUE TITLE
Support to configure the application using a configuration file

### ISSUE THREAD

**Issue by kxcasa** [pact-foundation/pact-broker-chart#2]
According to Pact Broker [documentation](https://docs.pact.io/pact_broker/configuration/settings), the configuration can be exposed to the application using a configuration file, whose path is indicated by the environment variable PACT_BROKER_CONF. This would be a more secure way of exposing secrets to the application than via environment variables.

**Comment by ChrisJBurns** [comment]
@kbcasagrande  Thanks for this. Although the Docker image for the Broker doesn't have said config file by default. We could probably do some thinking around creating the file via ConfigMap. Although I'm curious why you think exposing it via a Config file is more secure than environment variables? Once someone has access to the Pact Broker container, they have access to the environment variables in the same way they have access to the config file?

**Comment by kxcasa** [comment]
Hey Chris,
I gives more security due to:
 - The environment variables content can be seem by just describing the deployment;
 - Permissions can be set for Secrets;
 - Some applications when dumping its stack, dump also the environment. Due to this using Secret files is recommended for exposing sensitive data to the application;
 
Considering that there can be only one configuration file and it contains sensitive information, I'd use a Secret instead of a ConfigMap.

**Comment by ChrisJBurns** [comment]
Ah, I use SOPS with Flux to install my charts so I don't tend to have the environment variable problems as much. However, you make some good points, happy to accept a PR to see what you're thinking?

**Comment by kxcasa** [comment]
Here, we use SOPS as well integrated into another CD solution. I will submit a PR addressing some configuration related topics.

**Comment by ChrisJBurns** [comment]
@kbcasagrande Great, thank you! Look forward to seeing it!
