### ISSUE TITLE
RevisionHistoryLimit should be configurable

### ISSUE THREAD

**Issue by knechtionscoding** [pact-foundation/pact-broker-chart#24]
RevisionHistoryLimit can be useful to change from the default of 10 for UX reasons. Being able to configure that inside the chart would be helpful

**Comment by ChrisJBurns** [comment]
Hi @KnechtionsCoding  has the Pact Broker got an environment variable for setting this?

**Comment by ChrisJBurns** [comment]
This has been implemented via https://github.com/pact-foundation/pact-broker-chart/pull/25
