### ISSUE TITLE
If `serviceAccount.create` is false, `serviceAccount.name` is required to be set

### ISSUE THREAD

**Issue by rmartine-ias** [pact-foundation/pact-broker-chart#41]
In prior chart versions, I was able to set `serviceAccount.create: false`, and that was the end of things. As of latest, this fails with the error: 

```
Error creating: pods "pact-broker-xxxxxxx-" is forbidden: error looking up service account pact-broker/broker-sa: serviceaccount "broker-sa" not found
```

This is fixed by setting `serviceAccount.name: default`. This may be working as intended, but IMO if I say "Don't create a service account", and don't specify a service account name, the default name should be used.

Ref: https://github.com/pact-foundation/pact-broker-chart/pull/26

**Comment by ChrisJBurns** [comment]
You're correct, by default it should set the name to `default` if the `serviceAccount.create` is set to `false`. I will submit a fix to correct the default value of `serviceAccount.name` to `default`. Instead of `broker-sa`.

**Comment by ChrisJBurns** [comment]
@rmartine-ias  Thank you for raising the issue, give `0.7.1` a try :)

**Comment by rmartine-ias** [comment]
Thank you for the quick fix! Will try it out next round of helm-chart upgrades in a few weeks :)
