### ISSUE TITLE
Values link  typo

### ISSUE THREAD

**Issue by AliakseiVenski** [pact-foundation/pact-broker-chart#6]
[templates](https://github.com/ChrisJBurns/pact-broker-chart/tree/master/charts/pact-broker/templates)/_helpers.tpl:
Line 82: 
.Values.externalDatabase.config.auth.**user** 

should be:
.Values.externalDatabase.config.auth.**username**

Just additional question - do we really need .Values.externalDatabase.config.auth.password ? It isn't used anywhere.

**Comment by ChrisJBurns** [comment]
Yes you're right regarding the `user` -> `username` part, feel free to submit a PR, if not, I can fix when I'm free (which shouldn't be too long)

On the password point, is also a good point, I think there's just a missing condition [here](https://github.com/ChrisJBurns/pact-broker-chart/blob/master/charts/pact-broker/templates/deployment.yaml#L70) that checks if the `.Values.externalDatabase.config.auth.password` field is present, and if so, to use it.
