### ISSUE TITLE
Unable to set Pact Broker Context path

### ISSUE THREAD

**Issue by manali14** [pact-foundation/pact-broker-chart#68]
We are trying to set the env variable PACT_BROKER_BASE_URLS to set a context path for running the broker at a custom endpoint, but looks like the variable is misconfigured in the helm chart. It should be PACT_BROKER_BASE_URL.

By setting PACT_BROKER_BASE_URLS to a custom path, the css & js gets loaded from that path, but it's still accessible on /

Also, in ingress there is no way to set any other Prefix other than /, so its difficult to configure pact to a custom path, considering we can't customize ingress or pass custom env variables to the helm chart

**Comment by manali14** [comment]
@ChrisJBurns Can you take a look at it? Is that something planned to be implemented soon?

**Comment by ChrisJBurns** [comment]
Hi @manali14 so I'd raise the Ingress issue and custom env vars separately if that's ok? Just so we can attach the right PR to them.

With regards to the `PACT_BROKER_BASE_URLS` vs `PACT_BROKER_BASE_URL`, I'm not sure if I understood what you're asking, are you saying that we have to rename `PACT_BROKER_BASE_URLS` to `PACT_BROKER_BASE_URL`?

**Comment by manali14** [comment]
@ChrisJBurns Yes, should be fine

With regards to the PACT_BROKER_BASE_URLS vs PACT_BROKER_BASE_URL, the pact official docker image accepts the latter env variable as mentioned here: https://hub.docker.com/r/pactfoundation/pact-broker#:~:text=PACT_BROKER_BASE_URL but the helm chart isn't compatible with this change & not allowing to set the context path

**Comment by ChrisJBurns** [comment]
@manali14  I have resolved the environment variable issue, would you be able to raise the separate issues for the ingress as the extra env vars?

**Comment by manali14** [comment]
@ChrisJBurns That's still not working, after setting that env var, the application is not accessible on /pact

Tried the below from inside the pod
 wget 127.0.0.1:9292/ -- This works
 wget 127.0.0.1:9292/pact -- This doesn't (Ideally this should work)

**Comment by ChrisJBurns** [comment]
Hmm, if the variable is being set, not sure if there's much we can do in the Helm chart :( you may have to raise it on the Pact Slack? There may be some common issues people have with it?
