### ISSUE TITLE
SAML Support or Github Authentication

### ISSUE THREAD

**Issue by sridhar-parvathala** [pact-foundation/pact-broker-chart#7]
Good Day @ChrisJBurns 

I appreciate you providing the helm chart, I intend to use it and am investigating the pact broker authentication possibilities.

Does it allow for GitHub or SAML authentication?

Can we use this chart for production? Thank you for any suggestions.

**Comment by ChrisJBurns** [comment]
Hi @sridhar-parvathala 

Unfortunately not. The underlying Pact Broker itself doesn't support any other forms of login outside of the admin and read users. So there's nothing that we can do in the Chart to resolve this.

There are other methods of hiding Pact behind some authentication such as a proxy, but natively the Pact Broker doesn't support anything outside of the standard admin and read user

**Comment by sridhar-parvathala** [comment]
Thank you @ChrisJBurns  for your prompt response.

**Comment by ChrisJBurns** [comment]
Closing due to conversation above.
