### ISSUE TITLE
Possibility to switch oo basicAuth

### ISSUE THREAD

**Issue by ekorladinov** [pact-foundation/pact-broker-chart#9]
We are using pact broker in a secured perimeter and would like to have the possibility to switch off basicAuth.

Thank You

**Comment by ChrisJBurns** [comment]
Hi @ekorladinov this should be fine, just set [the following value](https://github.com/ChrisJBurns/pact-broker-chart/blob/master/charts/pact-broker/values.yaml#L138) to `true` and it will disable the `basicAuth`. You will however still need credentials in order to write to the broker.

**Comment by ekorladinov** [comment]
Hi Chris, 
We want to switch off basic auth completely - read and write

**Comment by ChrisJBurns** [comment]
Hi @ekorladinov I believe your answer is somewhere in the [Pact Broker docs](https://docs.pact.io/pact_broker/configuration/settings#authentication-and-authorization) - possibly the `basic_auth_enabled` flag. This Helm Chart just allows you to specify the environment variables and configuration that maps to the config that the Pact Broker uses. The Helm chart isn't able to do anything in the realms of modifying Pact Broker behaviour as that's all abstracted into the Pact Broker code. We can only provide it the configuration parameters that we want it to use.

**Comment by ekorladinov** [comment]
Hi Chris, basic_auth_enabled is not exposed in values.yaml and is not possible to set it up

**Comment by ChrisJBurns** [comment]
@ekorladinov You're right, I shall add it :) (apologies, I assumed it was added by a PR previously)

**Comment by ekorladinov** [comment]
Chris, thank you very much

**Comment by ChrisJBurns** [comment]
@ekorladinov  Have released a new version of the Chart `0.2.0`. When it's available, give it a pull :+1:
